name: Build and Deploy GitHub Pages Windows

on:
  push:
    branches:
      - main  # Change to your main branch name

jobs:
  deploy:
    runs-on: self-hosted  # Use a self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2