name: Build and Deploy GitHub Pages Windows

on:
  push:
    branches:
      - main  # Change to your main branch name

jobs:
  deploy:
    runs-on: self-hosted  # Use a self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        run: |
          #choco install ruby --version=2.7.4
          refreshenv
          gem install bundler
          bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        run: |
          # Assuming your Jekyll site is in the "_site" directory
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout -b main
          git add -f _site  # Force add to overcome the .gitignore
          git commit -m "Build Jekyll site"
          git push origin main
